remote_theme: andrewbanchich/forty-jekyll-theme
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-relative-links

theme_mode: dark
title: Coco
iconURL: "kiti.png"
domain: my-site.github.io
url: https://callmecocogrr.github.io
baseUrl: /blog/
social:
  github: CallMeCocoGrr